spring:
  profiles:
    active: dev
  jpa:
    open-in-view: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /

logging:
  file:
    name: ./log/app.log
  level:
    root: info
